---
- name: Install nginx
  dnf:
    name: nginx
    state: present

- name: Enable and start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy nginx reverse-proxy.conf
  template:
    src: reverse-proxy.conf.j2
    dest: /etc/nginx/conf.d/reverse-proxy.conf
    owner: root
    group: root
    mode: '0644'

- name: Deploy static index.html
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: Test nginx config syntax
  command: nginx -t
  register: nginx_test_result
  failed_when: nginx_test_result.rc != 0
  changed_when: false

- name: Reload nginx
  command: nginx -s reload